apiVersion: v1
kind: Pod
metadata:
  name: game-pod-{{ .Release.Name }}
  labels:
    app: game-pod-{{ .Release.Name }}
spec:
  containers:
  - name: rtsp-node
    image: geonhyukseo/goormnes-streaming:3c6b796b71897ac58834be626b723b31a6d829f7
    env:
      - name: MTX_PATH
        value: mtx-service-{{ .Release.Name }}
    ports:
    - containerPort: 2000
  - name: nes
    image: geonhyukseo/goormnes:4bc4e4a2863f6af659b9418d4b02db55bbc79e81
    ports:
    - containerPort: 8080
  - name: mediamtx
    image: bluenviron/mediamtx:latest
    env:
    - name: MTX_PROTOCOLS
      value: tcp
    ports:
    - containerPort: 8554
    - containerPort: 1935
    - containerPort: 8888
    - containerPort: 8889
    - containerPort: 8890
    - containerPort: 8189
