apiVersion: v1
kind: Pod
metadata:
  name: game-pod-{{ .Release.Name }}
  labels:
    app: game-pod-{{ .Release.Name }}
spec:
  containers:
  - name: mediamtx
    image: bluenviron/mediamtx:latest
    env:
    - name: MTX_PROTOCOLS
      value: tcp
    ports:
    - containerPort: 8554
    - containerPort: 1935
    - containerPort: 8888
    - containerPort: 8889
    - containerPort: 8890
    - containerPort: 8189
  - name: nes
    image: geonhyukseo/goormnes:4bc4e4a2863f6af659b9418d4b02db55bbc79e81
    ports:
    - containerPort: 8080
  - name: rtsp-node
    image: geonhyukseo/goormnes-streaming:c197b29c2d969a01a39d5b2162972c8d61e68c1a
    env:
      - name: WS_PATH
        value: {{ .Values.uniquePath }}
    ports:
    - containerPort: 2000
