{{- if not .Values.uniquePath }}
{{- fail "httpPath 값은 반드시 제공되어야 합니다. 게임 파드 생성 실패" }}
{{- end }}
---
apiVersion: v1
kind: Pod
metadata:
  name: game-pod
  labels:
    app: game-pod
spec:
  containers:
  - name: rtsp-node
    image: geonhyukseo/goormnes-streaming:8d85f45df5d81495f4a73184d9d315a6e9c3e99e
    ports:
    - containerPort: 2000
  - name: nes
    image: geonhyukseo/goormnes:4bc4e4a2863f6af659b9418d4b02db55bbc79e81
    ports:
    - containerPort: 8080
  - name: mediamtx
    image: bluenviron/mediamtx:latest
    env:
    - name: MTX_PROTOCOLS
      value: tcp
    ports:
    - containerPort: 8554
    - containerPort: 1935
    - containerPort: 8888
    - containerPort: 8889
    - containerPort: 8890
    - containerPort: 8189