apiVersion: v1
kind: Service
metadata:
  name: game-service-{{ .Release.Name }}
spec:
  selector:
    app: game-pod-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000
  type: ClusterIP
