apiVersion: v1
kind: Service
metadata:
  name: game-service-{{ .Release.Name }}
  labels:
    app: game-pod-{{ .Release.Name }}
spec:
  selector:
    app: game-pod-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
    - protocole: TCP
      port: 1201
      targetPort: 1201
    - protocole: TCP
      port: 1014 
      targetPort: 1014 
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mtx-service-{{ .Release.Name }}
spec:
  selector:
    app: game-pod-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8554
      targetPort: 8554
  type: ClusterIP

