apiVersion: v1
kind: Pod
metadata:
  name: game-pod-{{ .Release.Name }}
  labels:
    app: game-pod-{{ .Release.Name }}
spec:
  containers:
  - name: mediamtx
    image: bluenviron/mediamtx:latest
    env:
    - name: MTX_PROTOCOLS
      value: tcp
    ports:
    - containerPort: 8554
    - containerPort: 1935
    - containerPort: 8888
    - containerPort: 8889
    - containerPort: 8890
    - containerPort: 8189
  - name: nes
    image: {{ .Values.nes.image.name }}:{{ .Values.nes.image.tag }}
    ports:
    - containerPort: 8080
  - name: nes-streaming
    image: {{ .Values.nesstreaming.image.name }}:{{ .Values.nesstreaming.image.tag }}
    env:
      - name: WS_PATH
        value: {{ .Values.uniquePath }}
    ports:
    - containerPort: 2000
