{{- if not .Values.uniquePath }}
{{- fail "httpPath 값은 반드시 제공되어야 합니다. 인그레스 클래스 생성 실패" }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: game-ingressclass
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
spec:
  controller: k8s.io/ingress-nginx